name: Fetch Google Analytics Data (GA4)

on:
  workflow_dispatch:

jobs:
  fetch-analytics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          npm install googleapis@105 @google-cloud/local-auth@2.1.0 --save
          npm install @google-analytics/data

      - name: Fetch Google Analytics 4 Data
        env:
          GA_PROPERTY_ID: ${{ secrets.GA_PROPERTY_ID }}
          SERVICE_ACCOUNT_KEY: ${{ secrets.GA_SERVICE_ACCOUNT_KEY }}
        run: |
          node -e "
            const fs = require('fs');
            const { BetaAnalyticsDataClient } = require('@google-analytics/data');

            // Debug: log the SERVICE_ACCOUNT_KEY
            console.log('SERVICE_ACCOUNT_KEY:', process.env.SERVICE_ACCOUNT_KEY);

            // Retrieve and parse the service account key from the environment variable
            const keys = JSON.parse(process.env.SERVICE_ACCOUNT_KEY);

            async function runReport(propertyId) {
              const analyticsDataClient = new BetaAnalyticsDataClient({ credentials: keys });

              try {
                const [response] = await analyticsDataClient.runReport({
                  property: 'properties/' + propertyId,
                  dateRanges: [{ startDate: '30daysAgo', endDate: 'today' }],
                  dimensions: [{ name: 'city' }],
                  metrics: [{ name: 'activeUsers' }]
                });

                // Extract the report data
                const reportData = response.rows.map(row => ({
                  city: row.dimensionValues[0].value,
                  activeUsers: row.metricValues[0].value
                }));

                console.log('Report result:', reportData);
                fs.writeFileSync('visits.json', JSON.stringify({ data: reportData }, null, 2));
                console.log('visits.json content:', JSON.stringify({ data: reportData }, null, 2));
              } catch (error) {
                console.error('Error fetching GA4 data:', error);
              }
            }

            runReport(process.env.GA_PROPERTY_ID);
          "
