name: Fetch Google Analytics Data (GA4)

on:
  workflow_dispatch:

jobs:
  fetch-analytics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          npm install googleapis@105 @google-cloud/local-auth@2.1.0 --save
          npm install @google-analytics/data

      - name: Fetch Google Analytics 4 Data
        env:
          GA_SERVICE_ACCOUNT_KEY: ${{ secrets.GA_SERVICE_ACCOUNT_KEY }}
          GA_PROPERTY_ID: ${{ secrets.GA_PROPERTY_ID }}
        run: |
          echo "$GA_SERVICE_ACCOUNT_KEY" > service-account.json
          node -e "
          const fs = require('fs');
          const {BetaAnalyticsDataClient} = require('@google-analytics/data');

          const CREDENTIALS_PATH = 'service-account.json';

          // Load credentials from service account JSON file
          const content = fs.readFileSync(CREDENTIALS_PATH, {encoding:'utf8', flag:'r'});
          const keys = JSON.parse(content);

          async function runReport(propertyId) {
              const analyticsDataClient = new BetaAnalyticsDataClient({credentials: keys});

              try {
                  const [response] = await analyticsDataClient.runReport({
                      property: 'properties/' + propertyId,
                      dateRanges: [
                          { startDate: '30daysAgo', endDate: 'today' },
                      ],
                      dimensions: [{ name: 'city' }],
                      metrics: [{ name: 'activeUsers' }]
                  });

                  // Extract the report data
                  const reportData = response.rows.map(row => ({
                      city: row.dimensionValues[0].value,
                      activeUsers: row.metricValues[0].value
                  }));

                  // Print report to stdout for debugging
                  console.log('Report result:', reportData);

                  // Save report data to a JSON file
                  fs.writeFileSync('visits.json', JSON.stringify({ data: reportData }, null, 2));

                  // Print the contents of visits.json to stdout for debugging
                  console.log('visits.json content:', JSON.stringify({ data: reportData }, null, 2));
              } catch (error) {
                  console.error('Error fetching GA4 data:', error);
              }
          }

          runReport(process.env.GA_PROPERTY_ID);
          "

          rm service-account.json  # Remove the service account file after use

      - name: Commit updated data
        run: |
          git config --global user.name "MilanKacar"
          git config --global user.email "actions@github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add visits.json
            git commit -m "Update visit count"
            git push
          else
            echo "No changes to commit"
          "
