name: Rebuild GitHub Pages on Visits.json Update

on:
  push:
    paths:
      - "visits.json"

jobs:
  rebuild:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Trigger site rebuild
        run: |
          git config --global user.email "milankacar@glive.com"
          git config --global user.name "GitHub Action"
          git checkout main
          echo "rebuild_trigger: $(date)" >> _config.yml
          git add _config.yml
          git commit -m "Trigger rebuild from visits.json change"
          git push origin main
