name: Track Visits

on:
  workflow_dispatch:
  push:
    branches:
      - main
  page_build:

jobs:
  update-counter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update visit count
        run: |
          current_count=$(cat visits.json | jq '.visits')
          new_count=$(($current_count + 1))
          echo "{\"visits\": $new_count}" > visits.json
      - name: Commit changes
        run: |
          git config --global user.name "MilanKacar"
          git config --global user.email "milankacar@glive.com"
          git add visits.json
          git commit -m "Increment visit counter"
          git push
